Nanoindent edit
emmateki/nanoindent_growth_measurment pull request #2
Opened 2023-11-15 18:55 UTC by emmateki

Ahoj,

rada by som poprosila o review.
Primárne som sa zamerala na nanoindents, ktoré som po tvojom nápade s args, mergla do jedného a menia sa tam len parametre pri volaní. Robila som to prvý krát, tak verím, že to je dobre. Fungovať to funguje ale to je už druhá vec :D
Zároveň som pomenila logging errorov.

Streamlit je úplne super knihovňa, je to jednoduchšie ako to GUI čo som robila predtým a podľa mňa aj prehľadnejšie a ľahšie na spustenie. Zatiaľ som tam len nahádzala veci tak aby to fungovalo. Takže keď to bude hotovo a budem s tým spokojná, dám PR.

Ďakujem

2023-11-15 19:44 UTC, jaroslavknotek reviewed
Test komentáře (viz teams)

2023-11-15 19:44 UTC, jaroslavknotek commented on app_streamlit.py
> +
My test comment

2023-11-15 19:44 UTC, jaroslavknotek commented on app_streamlit.py
> +    "Choose a folder with data:", key="-IN2-")
My test comment 2

2023-11-16 10:32 UTC, jaroslavknotek requested changes
Dobrý, jsou tam nějaky must-have.

2023-11-16 10:32 UTC, jaroslavknotek commented on main.py
> +            if VERSION == 'S':
Pokud budeš někdy aspirovat na hard-core programátora, tak si vzpomeň na if-less programming.

Jedná se o styl programování, kdy eliminuješ tenhle typ if. V programování větších věcí zvyšují tenhle typ IF komplexitu programu. Ideálně (stejně jako s tím loggingem) chceš na začátku programu jasně  nadefinovat průchod a ten pak executnout. Nechceš mít nikde po cestě if, který ti dramaticky změní chování programu.

Těžko se to vysvětluje, pro juniory. Nicméně pokud chceš seriózně programovat větší věci a setkáš se s unit-testování, nebo objektově orientovaném programování, tak tam se řeší problémy, které tyto if způsobují a pak i řešení.

2023-11-17 20:59 UTC, jaroslavknotek commented on app_streamlit.py
> +    if selected_folder:
To nevím. Nechám na tobě.

Když to vyšpekruješ, tak se tím můžeš chlubit, ale může se stát, že to nikdo nikdy neotevře... naopak je špatný tutoriál může usery (mimo řež - ty co si tě najdou na githubu) odradit.

2023-11-17 21:36 UTC, jaroslavknotek reviewed
Za mě dobrý. 
Objevil jsem ale chyby týkající se control flow programu. Otestuj program se složkama kde
1) chybí obrázkek před, po, oba 
2) jeden obrázek je špatnej (vytvoř prázný txt a přejmenuj ho na validní název orbázku). On nepůjde přečíst a program si nebude vědět rady. Měl by ti dát jasně najevo, co s tim nefunguje.

Jsou to problémy na které dřív nebo či později někdo narazí. 

Pokud to **teď** nechceš už řešit, tak nemusíš. Nicměně by ses k tomu měla vrátit dřív, než zapomeneš na to, jak ten program byl psanej. Pokud ne, tak se může stát, že budeš opravovat software, kterej si už nepamatuješ a pak to jde blbě.

Jinak je to výarzně lepší než to bylo. Po vyřešení chyb s control flow to bude moc pěknej kód.

2023-11-17 21:36 UTC, jaroslavknotek commented on indentation_reader.py
> +Credit to Jaroslav Knotek for the following functions:
Tak to tu resolvni, ať se to neplete mezi otevřené konverzace

2023-11-17 21:36 UTC, jaroslavknotek commented on main.py
> +            if VERSION == 'S':
Python je skvělej proto, že classam se můžeš vyhnout. Tohle je debata na dýl, pokud chceš, tak si můžem do detailu probrat ideální architekturu tohohle projektu do větší míry než takhle přes komentáře.

2023-11-17 21:36 UTC, jaroslavknotek commented on main.py
> +            img, 450, 720, 500, 820)
konstanty

2023-11-17 21:36 UTC, jaroslavknotek commented on shared.py
> +def log_error(folder_name, error_message):
Takhle dobrý. Všimni si, že se všim tim nastavením jsi vzala jednořádkovou metodu `logging.error(...)` obalila jinou metodou `log_error(...)`, která žije v separátním modulu, má svůj docstring atd... V každém modulu pak musíš ještě zavolat `import shared` atd.

Tzn ten tradeoff se už spíš nevyplatí. Nic nemusíš měnit.

Pokud bys to chtěla udělat pořádně (at už teď nebo v příštím projektu), tak se dají udělat dvě věci (klidně obě).

1) v top-level kódu zaloguješ `logging.info("processing {folder_name}")` a pak všechny chyby budou v kontextu této složku. Tento přístup má hromadu problémů. První je, že logging.info() nejde vidět, dokud nezměníš log_level ... 
2) pokud máš nutkání říct, která část nefunguje, tak to typicky znamená, že ta chuyba znemožnujě zpracování celý složky. Pokud to je pravda, tak se to dělá jinak.

Pseudo kód:

```
def top_level_process_folder(folder_name):
  logging.info(f"processing {folder_name}") ) # case-1
  try:
    sub_level_stuff(...)
  except Exception:
    logging.exception(f"Error while processing {folder_name}"

def sub_level_stuff(...):
  ...
  if somethings_is_not_right:
     # neloguj,že se něco stalo špatně tady
     # return # neukončuj program, když se stalo něco špatně
     # namísto toho vyhoď vyjíku, která je mění flow programu
     raise Exception("Stalo se něco co se stát nemá")

```

Pokud ten error nenaruší zpracování, tak je to spíš warning. 

Dole zkusím vypíchnout konkrétní příklad


links:
[logging.exception](https://stackoverflow.com/a/5191885/3228432)

2023-11-17 21:36 UTC, jaroslavknotek commented on indentation_reader.py
> +        log_error(folder_name, error_message)
Exception:

Zaloguješ error a neukončíš program, tzn hned na dalším řádku načítáš neexistující obrázek.

2023-11-17 21:36 UTC, jaroslavknotek commented on indentation_reader.py
> +        return None
Exception:

Co se stane později v programu, když tenhle obrázek nevyhovuje a tak radši vrátíš `None`?

Pokud je to kritická chyba, která by měla přerušit zpracování, tak vyhoď vyjímku, může to být lepší control flow než vracet `None`

2023-11-17 21:36 UTC, jaroslavknotek commented on indentation_reader.py
> +        log_error(folder_name, error_message)
Opět, zaloguješ chyby, ale pak pokračuješ v zpracování, kde to pak spadne na řádku 57.

Zkus si seběhnout program s chybějícími obrázku. Objevíš pak bizarní chování a nesmyslné errory.

Třeba, když program spadne tady, tak v outputu uvidíš:

...
1)zalogovaný error: "No matching img'
2)python exception: List index 0 out of range.

Někdo kdo debuguje software typicky kouká na poslední řádek kterej mluví o chybě, která je vlastně o něčem jiném.

Kdyby tam bylo
`raise Exception("Missing after image")`

Tak je to i to poslední co user v konzoli/logu uvidí.

2023-11-17 21:36 UTC, jaroslavknotek commented on main.py
> +from shared import configure_logger
Pokud se rozhodneš smazat metodu `log_error`. Tak v `shared` zůstane jenom `configure_logger`. Ta metoda je volaná pouze odsud a tak se ta metoda může přesunout sem.

2023-11-21 12:55 UTC, emmateki reviewed
Ahoj, 

konštaty som hodila do config, zmenila som  error handeling keď chýba file aby to bolo jasné. Teraz priamo do aplikácie vyhodí pekne červené hlásenie s tým, že chýba file alebo má zlý formát.

2023-11-21 12:55 UTC, emmateki commented on app_streamlit.py
> +    if selected_folder:
Super nakoniec som to nechala tak, nie je to dlhé a na základné otázky by to malo odpovedať.

2023-11-21 12:55 UTC, emmateki commented on shared.py
> +def log_error(folder_name, error_message):
Nie som si úplne istá, že chápem, pozriem si to na internete, keď tak by sme sa o tom mohli pobaviť, kebyže dohdoneme call o ideal architektúre projektu ?

2023-11-21 12:55 UTC, emmateki commented on indentation_reader.py
> +        log_error(folder_name, error_message)
DONE

2023-11-23 15:48 UTC, jaroslavknotek requested changes
Super! Ten kód se výrazně lepší. Vidim tam jenom kus kódu o kterym si myslím, že je to bug (označeno `BUG!`).

Pak jsem přidal hromadu menších komentářů ohledně drobností a jeden velkej komentář ohledně architektury. Nicméně se jedná jen o drobnosti/zajímavosti. 

Až fixneš ten bug, tak dám "approved".

Nezapoměň, že není nutné pushovat po každém commitu. Stačí jednou

2023-11-23 15:48 UTC, jaroslavknotek commented on main.py
> +                if folder_name:
BUG!
Celej tenhle kus kódu je dost smelly.

Máme dataframe `df`, kterej nějak vzniknul v `indentation_reader.read_data()`. Pak někde, pomocí uplně jinýho kusu kódu načteš složky `folder_name` z `data_root_path` pak je spojuješ pomocí

```
row = df.iloc[j]
folder_name = folder_names[j]
```

Tady je několik problémů:
1) Pokud jsi [encapsulovala](https://en.wikipedia.org/wiki/Encapsulation_(computer_programming)) načítání dat do nějaké třídy, tak jsi "ztratila" zájem a kontrolu nad tím jak tato metoda přesně pracuje. Důsledkem je, že nemusíš vědět v jakém pořadí to plní ten dataframe a jestli to náhodou nepřeskakuje prázdné složky atd... Pokud se budem držet zásad dobrého programování, tak to nevíš
2) Donačítáš si vedlejší data `folder_names` v nějakém pořadí daným implementací `iterdir` a s filterem `isdir()`. Tvým cílem bylo __nezávisle__ donačíst nějaká data k tomu datasetu, ale pokud platí pravidlo encapsulace, tak nevíš jak to udělala metoda `read_data` a může dojít k desynchronizaci. Ve folder_names může být více či méně záznámu a nebo stejně, přičemž můžou být v jiném pořadí. Co se tam ale nemůže objevit, je None, nebo prázdný řetězec `''`, který tu kontroluješ. Pokud by na indexu `j` nic nebylo, tak `folder_names[j]` vyhodí index out of bound exception. Celý `if/else` postrádá smyslu.

Řešení je několik (nevím proč generuješ folder_name)
1) Upgraduješ metodu `read_data` tak, aby to obsahovalo to co potřebuješ (tzn dataframe bude míť navíc sloupec `folder_name` (což podle mě už má ne? `pathlib.Path(row.img_before).parent`?. Pokud jsi na projektu sama, tak je to nejlepší řešení. Kdyby tu metodu používal někdo jiný, tak mu tím můžeš něco rozbít.
2) Uděláš [wrapper](https://en.wikipedia.org/wiki/Wrapper_function) tzn funkci `read_data_with_folder_names()` kde zavoláš read_data a pro každý řádek doplníš folder name a vrátíš.
```
def read_data_w_folder_names():
    df = indentaiton_reader.read_data()
    folder_naems = []
    for row in df.iterrows():
         folder_name =# code that finds folder_name for given row
         folder_names.append(folder_name) 
    return folder_names, df # bud a nebo
    df['folder_name]=folder_names
    return df
```
Tohle je ve větších projektech preferovaný způsob, kdy zachováš původní chování, ale zároveň docílíš svého -> máš funkci která dělá přesně to co chceš.

2023-11-23 15:48 UTC, jaroslavknotek commented on main.py
> +    log_file_path = log_folder / "error.log"
pokud se proměná `log_folder` nepoužívá, tak můžeš
```
log_file_path = out_folder/"ERROR"/"error.log"
```

2023-11-23 15:48 UTC, jaroslavknotek commented on main.py
> +    if not log_file_path.exists():
Volat `log_file_path.parent.mkdir(parents=True, exist_ok=True)` můžeš i mimo if. POkud tomu dáš `exist_ok = True`, tak je to [idenpotentní](https://en.wikipedia.org/wiki/Idempotence) tzn nemusíš se bát, že se něco rozbije, když to zavoláš dvakrát.

Proč potom inicializuješ ten error log s nějakým textem?
Usera/operátora může máš, že i když mu celej běh programu proběhl v pořádku, tak stejně má nějakou složku ERROR v místě, kde má i logy.

2023-11-23 15:48 UTC, jaroslavknotek commented on main.py
> +            logging.error(f"{e}")
Tady jsou tři taby. Měly by být dva.

Pokud chceš tento typ chyb eliminovat, tak doporučuju formattery/lintery, které se starají o aplikovaní konvencí na formátování kódu : black,isort,ruff

Mám zkušenosti s black,isort ale moc to nepoužívám i když bych měl.

2023-11-23 15:48 UTC, jaroslavknotek commented on main.py
> +            log_error(folder_name, error_message)
log_error ->logging.error

2023-11-23 15:48 UTC, jaroslavknotek commented on main.py
> +        nan_count = np.isnan(grid_remove_points[:, :, 1]).sum()
Pěkný!

2023-11-23 15:48 UTC, jaroslavknotek commented on main.py
> +            log_error(folder_name, error_message)
Zvaž, jestli se nehodí víc vyhodit exception.

2023-11-23 15:48 UTC, jaroslavknotek commented on main.py
> +            else:
Tady je pěkně vidět, jaký jsou`if` problém.

V tuto chvíli se kód nachází na úplném konci a je tady nějaký `if version == xxx`. Je to jedno z více míst, kde se if version == xxx nachází. 

1) pokud by ses rozhodla přidat ještě jeden typ verze, tak musíš updatovat kód na mnoha místech zároveň. (vyhledávala bys pomocí find a to není uplně cool). Navíc tvůj kód může někdo importovat a tam už nic nezměníš.
2) Představ si, že bys takhle změnila všechno, ale zapoměla bys na tohle jedno místo. Pokud to testuješ klikáním, tak se to dozvíš až uplně na konci běhu a to není ideální.


Proto se implementují různé [design patterns](https://en.wikipedia.org/wiki/Design_Patterns), které tento problém řeší. Určitě to teď neimplementuj, pokud nechceš.

Jedním z nich může být [command](https://en.wikipedia.org/wiki/Command_pattern). Pomocí toho si enacpsuluješ zpracování obou verzí seprátně a pak si to jenom zavoláš. 

----

Příklad:
Mám verzi "S" a "M", které se liší v načítání a ukládání dat.

Tvůj program vypadá následovně: máš n=2 `if` a m=2 `version`s

```
# start
if version == "S":
   data = load_s()
elif version == "M":
   data = load_m()
else:
   raise Exc("unknown version")

result = process(data)

if version == "S":
    save_s()
elif version == "M":
    save_m()
else:
    raise Exc()
# END
```

Pokud budeš chtít přidat další verzi, tak musíš upravovat `n` ifů a pokud chceš přidat další větvení, tak řešíš 1 if pro `m` verzí. Navíc máš ještě `n`-krát napsánou else větev. 

Řešení
```
# deklarace
class CommandVersionSmall:
   def load_data():
        # pass
   def save_data():
        # pass
class CommandVersionMedium:
   def load_data()
       # pass
   def save_data
       # pass
# preparations
if version = "s":
   version_command = VersionCommandSmall()
elif version =='M":
   version_command = VersionCommandMedium()
else
   raise exception()
# start 
data = version_command.load_data()
result = process(data)
version_commad.save_data()
#end
```

Všimni si, že část prepocesingu je to, kde si připravuješ vše pro běh a čášt "start" až do "end" je uplně tenoučká, dobřé se čte a není tam žáďný IF. If bylo vyřešeno nazačátku. 

V kódu se pak nic nemění. 

Tohle byl jen teaser. Pokud tě to zajímá, tak doporučuji
1) projíť si ty [GoF design patterns](https://en.wikipedia.org/wiki/Design_Patterns)
2) zkusit na nějakym menším prototypu, kde zkušíš začít s kódem výše (2 if, 2 metody) a zkusíš si přidat jednu další metodu (process_s,process_m) a pak ještě jednu verzi ("L") a tam uvidíš, jak každej If bolí. Pak to přepíše3 pomocí toho co jsem nastínil. 
3) pak se podíváš na [dědičnost](https://en.wikipedia.org/wiki/Inheritance_(object-oriented_programming) kterou je důležitý pochopit dřív než se pustíš do úpravy produkčního kódu, aby nedocházelo k duplikování kódu - Třeba v situaci,kdy save_s a save_m jsou z 95% procent stejný.

2023-11-24 09:34 UTC, jaroslavknotek commented on main.py
> +            else:
Existuje ještě jedna, méně náročná verze, kterou bych ti doporučil. Hodí se v případech, že to `n` i `m` je velmi malé.

```python
def process_version(version):
    if version=='s':
       data = load_s()
       res = process(data)
       save_s(res)
    elif version =='m':
       data = load_m()
       res = process(data)
       save_m(res)
    else:
       raise Exc()

```

Tohle si můžeš dovolit pouze tehdy, pokud ty metody `load_*` a `save_*` jsou "na stejné úrovni programu". Tady to je na "stejné úrovni", protože máš metodu `process_version()` která se obecně načte// uloží data a processing deleguje na funkci `process`. 

K pochopená toho co je a není stejná úroveň vede úvaha, co se stane, když někde vmetodě `process` budeš muset znovu rozlišit mezi verzema. Pak se nabízí více řešení v závislosti na problému, do kterých teď nebudu zabývat. Důležitý je si uvědomit, že na `if` opatrně.

2023-11-24 09:37 UTC, jaroslavknotek commented on main.py
> +                logging.error ("Wrong version.")
tady radši vyhodit exception, kterou ten try catch na řádku 138 zpracuje

2023-11-28 14:53 UTC, jaroslavknotek commented on main.py
> +        for j in range(len(df)):
zip vezme dvě pole, a iteruje je obě "ve stejnou chvíli" a vrací ti prvky jako tuple
```
x = [ 1,2,3]
y = 'abc'
for item1,item2 in zip(x,y):
    print(item1,item2)
```
vypíše:
```
1 a
2 b
3 c
```

Perfektně se to hodí na tento use case. Je matoucí používat indexy tam kde nejsou třeba. Člověk pak přemejšlí proč a hledá důvod.

2023-11-28 15:32 UTC, jaroslavknotek approved these changes
Approved.

- Okomentoval jsem ti pár low-prio části, které není třeba měnit
- Kód neobsahuje tu změnu architektury, takže ta ohodnocená není.

2023-11-28 15:32 UTC, jaroslavknotek commented on main.py
> +        raise Exception(f"{e}")
Tohle funguje a dělá to co má, ale není to správně.

Pokud chytneš nějakou exception, něco s ní provedeš a chceš jí pak poslat dál, tak se to dělá dvěma jinak. Důvod proč je tohle nevhodný je ten, že přerušíš stack trace. Místo, aby ti to vypsalo že chyba je v `indentation_reader.py:XY`, tak ti to řekne `main.py:36`. To je místo, kde jsi tuhle exception vytvořila a jakákoliv stopa po původci chyby zmizí. Člověk se musí podívat do `indentation_reader.py:read_data` sám  a hledat, kde by ta chyba mohla vzniknout. Hodně to zpomaluje debugging.

Řeší se to dvěma způsoby v závislosti, co s tou exception děláš:
1) Pokud chceš jenom něco přečíst a zalogovat, tak jí prostě pošleš dál  tak jak je. E.g. nahradíš `raise Exception(f"{e}")` tímto `raise`. To raise tu poslední exception tak jak je.
2) Pokud chceš změnit její typ, tak použiješ exception chaining `raise MyMainException("Something bad happened") from e`. Na tohle asi jen tak nenarazíš, ale pomůže to pochopit, k čemu exception přesně jsou.

Pro připomenutí:
- Mění control flow - pokud nastane problém, tak se celý vykonávání kódu přeruší až do bodu, kde je nějakej except
- při správném použití popisují lokaci a příčinu problému tak, aby se dal problém rychle objevit a opravit

Více najdeš [zde](https://docs.python.org/3/reference/simple_stmts.html#raise), jsou tam i příklady těch stack traců.

2023-11-28 15:32 UTC, jaroslavknotek commented on main.py
> +            logging.error(
Teda! Takovej hnusnej copy paste.

```
msg  = f"Error processing {folder_name}: Not enough points detected."
logging.error(msg)
raise Exception(msg)
```

Mám to hezčí, bez kopírování a ještě navíc líp zformátovaný.

2023-11-28 15:32 UTC, jaroslavknotek commented on main.py
> +                logging.error(f"Error processing {folder_name}: Wrong version.")
copy cat
```
msg = f"Error processing {folder_name}: Wrong version."
...
```

2023-11-28 15:32 UTC, jaroslavknotek commented on main.py
> +        logging.error(f"Error processing {folder_name}: {str(e)}")
uvintř toho try máš chyby, které vypadí takto
```
Exception(f"Error processing {folder_name}: Wrong version.")
```

Ty je chytíš a vypíšeš:
```
except Exception as e:
    logging.error(f"Error processing {folder_name}: {str(e)}")
```
kde to `str(e)` je vlastně `Error processing {folder_name}: Wrong version.`. Tzn výsledek je error:
```
Error processing /path: Error processing /path: Wrong version.
```
Navíc ani nemusím o tom, že ten error je logovanej dvakrát, takže ve finále to vypadá takto

```
Error processing /path: Wrong version.
Error processing /path: Error processing /path: Wrong version.
```

---

Vzhlede k tomu, že jsi to napsala pomocí těch exception, tak 
a) můžeš se zbavit všech `logging.error`, které máš před `raise Exception`
b) Kdekoliv máš `raise Exception("Error processing {folder_name}: <some reason>"), tak můžeš upravit na `raise Exception("<some reason>"), protože to "Error processing {folder_name}" je tam už u toho loggingu na řádku 165. Zbavíš se spousty redundance a ten kód pak prokoukne.

Tohle se může zdát jako minimální detail, ale je to důvod, proč středně velké projekty umírají. V jednu chvílí je kód víc o tom bodrelu, než o logice. Představ si jen, že bys chtěla ulehčit práci operátorů a spolu s tím co je špatně jim říct, jak to vyřešit. To by znamenalo si každou error hlášku projít a upravit jí tak, ať je to jasný i důchodci. To jak je to napsaný teď ti dá víc práce a co hůř, ještě tě to zpomalí.

Vzhledem k tomu, že je to malinkatej projekt, tak to nemusíš měnit, ale pokud plánuješ dál programovat, tak ti osvojení těchto praktik může programování zrychlit i zpříjemnit a to i uživatelům.


 
```

2023-11-29 13:21 UTC, emmateki reviewed
Exceptions som upravila, už by nemali byť duplikáty. Idem merge. 

Ďakujem za kopu skvelých rád !

2023-11-29 13:21 UTC, emmateki commented on main.py
> +        logging.error(f"Error processing {folder_name}: {str(e)}")
Pri wrong version som zistila, že môžem error vyhodiť, lebo ako streamlit app sú tam len dev choice ak skúsi dať človek inú prehodí mu to na Small- čo je default. A ked ide cez command line tak tam sa mu to nepodarí predať ako argument lebo argument má choices len 'M' alebo 'S'.

Celé logging a exception som upravila ako si spominal. 

DONE

2023-11-29 13:22 UTC, merged